// 英検5級 重要単語
// id: 300～
// 春講習　8P

const WORDS_spring_word_verb02 = [
    // 動詞
{ id: 300, english: "speak",            kanji: "話す",           hiragana: "はなす",           category: "spring_word_verb02", emoji: "🗣️" },
{ id: 301, english: "speak English",    kanji: "英語を話す",      hiragana: "えいごをはなす",    category: "spring_word_verb02", emoji: "🇬🇧" },
{ id: 302, english: "speak Japanese",   kanji: "日本語を話す",    hiragana: "にほんごをはなす",  category: "spring_word_verb02", emoji: "🇯🇵" },
{ id: 303, english: "speak French",     kanji: "フランス語を話す", hiragana: "ふらんすごをはなす", category: "spring_word_verb02", emoji: "🇫🇷" },
{ id: 304, english: "speak Chinese",    kanji: "中国語を話す",    hiragana: "ちゅうごくごをはなす", category: "spring_word_verb02", emoji: "🇨🇳" },
{ id: 305, english: "sit down",         kanji: "座る",           hiragana: "すわる",           category: "spring_word_verb02", emoji: "🪑" },
{ id: 306, english: "stand up",         kanji: "立ちあがる",      hiragana: "たちあがる",        category: "spring_word_verb02", emoji: "🧍" },
{ id: 307, english: "write",            kanji: "書く",           hiragana: "かく",             category: "spring_word_verb02", emoji: "✏️" },
{ id: 308, english: "write a letter",   kanji: "手紙を書く",      hiragana: "てがみをかく",      category: "spring_word_verb02", emoji: "✉️" },
{ id: 309, english: "clean",            kanji: "掃除する",        hiragana: "そうじする",        category: "spring_word_verb02", emoji: "🧹" },
{ id: 310, english: "teach",            kanji: "教える",          hiragana: "おしえる",          category: "spring_word_verb02", emoji: "👩‍🏫" },
{ id: 311, english: "meet",             kanji: "会う",            hiragana: "あう",             category: "spring_word_verb02", emoji: "🤝" },
{ id: 312, english: "enjoy",            kanji: "楽しむ",          hiragana: "たのしむ",          category: "spring_word_verb02", emoji: "😄" },
{ id: 313, english: "help",             kanji: "助ける、手伝う",   hiragana: "たすける、てつだう", category: "spring_word_verb02", emoji: "🙌" },
{ id: 314, english: "stop",             kanji: "止める、やめる",   hiragana: "とめる、やめる",    category: "spring_word_verb02", emoji: "🛑" },
{ id: 315, english: "start",            kanji: "始める、始まる",   hiragana: "はじめる、はじまる", category: "spring_word_verb02", emoji: "🚀" },
{ id: 316, english: "begin",            kanji: "始める、始まる",   hiragana: "はじめる、はじまる", category: "spring_word_verb02", emoji: "▶️" },
{ id: 317, english: "cut",              kanji: "切る",            hiragana: "きる",             category: "spring_word_verb02", emoji: "✂️" },
{ id: 318, english: "run",              kanji: "走る",            hiragana: "はしる",            category: "spring_word_verb02", emoji: "🏃" },
{ id: 319, english: "buy",              kanji: "買う",            hiragana: "かう",             category: "spring_word_verb02", emoji: "🛒" },
{ id: 320, english: "sell",             kanji: "売る",            hiragana: "うる",             category: "spring_word_verb02", emoji: "🏷️" },
{ id: 321, english: "know",             kanji: "知っている",       hiragana: "しっている",        category: "spring_word_verb02", emoji: "💡" },
{ id: 322, english: "swim",             kanji: "泳ぐ",            hiragana: "およぐ",            category: "spring_word_verb02", emoji: "🏊" },
{ id: 323, english: "walk",             kanji: "歩く",            hiragana: "あるく",            category: "spring_word_verb02", emoji: "🚶" },
{ id: 324, english: "sing",             kanji: "歌う",            hiragana: "うたう",            category: "spring_word_verb02", emoji: "🎤" },
{ id: 325, english: "sing a song",      kanji: "歌を歌う",         hiragana: "うたをうたう",      category: "spring_word_verb02", emoji: "🎵" },
{ id: 326, english: "do",               kanji: "する",            hiragana: "する",             category: "spring_word_verb02", emoji: "✅" },
{ id: 327, english: "do my homework",   kanji: "宿題をする",       hiragana: "しゅくだいをする",  category: "spring_word_verb02", emoji: "📝" },
{ id: 328, english: "have",             kanji: "持っている、いる、ある、食べる、飲む", hiragana: "もっている、いる、ある、たべる、のむ", category: "spring_word_verb02", emoji: "🤲" },
{ id: 329, english: "read",             kanji: "読む",            hiragana: "よむ",             category: "spring_word_verb02", emoji: "📖" },
{ id: 330, english: "read a book",      kanji: "本を読む",         hiragana: "ほんをよむ",        category: "spring_word_verb02", emoji: "📚" },
{ id: 331, english: "read a newspaper", kanji: "新聞を読む",       hiragana: "しんぶんをよむ",    category: "spring_word_verb02", emoji: "📰" },
{ id: 332, english: "come",             kanji: "来る",            hiragana: "くる",             category: "spring_word_verb02", emoji: "👋" },
{ id: 333, english: "come in",          kanji: "入ってくる",       hiragana: "はいってくる",      category: "spring_word_verb02", emoji: "🚪" },
{ id: 334, english: "come home",        kanji: "家に来る",         hiragana: "いえにくる",        category: "spring_word_verb02", emoji: "🏠" },
{ id: 335, english: "come here",        kanji: "ここに来る",       hiragana: "ここにくる",        category: "spring_word_verb02", emoji: "📍" },
{ id: 336, english: "open",             kanji: "開ける",           hiragana: "あける",           category: "spring_word_verb02", emoji: "🔓" },
{ id: 337, english: "open the window",  kanji: "窓を開ける",       hiragana: "まどをあける",      category: "spring_word_verb02", emoji: "🪟" },
{ id: 338, english: "close",            kanji: "閉める",           hiragana: "しめる",           category: "spring_word_verb02", emoji: "🔒" },
{ id: 339, english: "close the door",   kanji: "ドアを閉める",     hiragana: "どあをしめる",      category: "spring_word_verb02", emoji: "🚪" },
{ id: 340, english: "shut",             kanji: "閉める",           hiragana: "しめる",           category: "spring_word_verb02", emoji: "🚫" },
{ id: 341, english: "carry",            kanji: "運ぶ",             hiragana: "はこぶ",           category: "spring_word_verb02", emoji: "📦" },
{ id: 342, english: "use",              kanji: "使う",             hiragana: "つかう",           category: "spring_word_verb02", emoji: "🔧" },
{ id: 343, english: "use a computer",   kanji: "コンピューターを使う", hiragana: "こんぴゅーたーをつかう", category: "spring_word_verb02", emoji: "💻" },
{ id: 344, english: "work",             kanji: "働く",             hiragana: "はたらく",          category: "spring_word_verb02", emoji: "💼" },
{ id: 345, english: "pass",             kanji: "取る、渡す",        hiragana: "とる、わたす",      category: "spring_word_verb02", emoji: "🤲" },
{ id: 346, english: "Pass me ~",        kanji: "〜を取ってください",  hiragana: "〜をとってください",  category: "spring_word_verb02", emoji: "👐" },
];
