const WORDS_spring_word_verb01 = [
  // 動詞
  { id: 347, english: "like", kanji: "好き", hiragana: "すき", category: "spring_word_verb01", emoji: "❤️" },
  { id: 348, english: "play", kanji: "〜する（スポーツ、楽器）", hiragana: "〜する", category: "spring_word_verb01", emoji: "🎾" },
  { id: 349, english: "play soccer", kanji: "サッカーをする", hiragana: "さっかーをする", category: "spring_word_verb01", emoji: "⚽" },
  { id: 350, english: "play basketball", kanji: "バスケットボールをする", hiragana: "ばすけっとぼーるをする", category: "spring_word_verb01", emoji: "🏀" },
  { id: 351, english: "play baseball", kanji: "野球をする", hiragana: "やきゅうをする", category: "spring_word_verb01", emoji: "⚾" },
  { id: 352, english: "play volleyball", kanji: "バレーボールをする", hiragana: "ばれーぼーるをする", category: "spring_word_verb01", emoji: "🏐" },
  { id: 353, english: "play tennis", kanji: "テニスをする", hiragana: "てにすをする", category: "spring_word_verb01", emoji: "🎾" },
  { id: 354, english: "play badminton", kanji: "バドミントンをする", hiragana: "ばどみんとんをする", category: "spring_word_verb01", emoji: "🏸" },
  { id: 355, english: "play video games", kanji: "テレビゲームをする", hiragana: "てれびげーむをする", category: "spring_word_verb01", emoji: "🎮" },
  { id: 356, english: "play the piano", kanji: "ピアノを弾く", hiragana: "ぴあのをひく", category: "spring_word_verb01", emoji: "🎹" },
  { id: 357, english: "play the guitar", kanji: "ギターを弾く", hiragana: "ぎたーをひく", category: "spring_word_verb01", emoji: "🎸" },
  { id: 358, english: "study", kanji: "勉強する", hiragana: "べんきょうする", category: "spring_word_verb01", emoji: "📝" },
  { id: 359, english: "study English", kanji: "英語を勉強する", hiragana: "えいごをべんきょうする", category: "spring_word_verb01", emoji: "🇬🇧" },
  { id: 360, english: "study Japanese", kanji: "国語（日本語）を勉強する", hiragana: "こくご（にほんご）をべんきょうする", category: "spring_word_verb01", emoji: "🇯🇵" },
  { id: 361, english: "study math", kanji: "算数（数学）を勉強する", hiragana: "さんすう（すうがく）をべんきょうする", category: "spring_word_verb01", emoji: "➕" },
  { id: 362, english: "study music", kanji: "音楽を勉強する", hiragana: "おんがくをべんきょうする", category: "spring_word_verb01", emoji: "🎵" },
  { id: 363, english: "study science", kanji: "理科を勉強する", hiragana: "りかをべんきょうする", category: "spring_word_verb01", emoji: "🧪" },
  { id: 364, english: "study social studies", kanji: "社会を勉強する", hiragana: "しゃかいをべんきょうする", category: "spring_word_verb01", emoji: "🗺️" },
  { id: 365, english: "study history", kanji: "歴史を勉強する", hiragana: "れきしをべんきょうする", category: "spring_word_verb01", emoji: "📜" },
  { id: 366, english: "eat", kanji: "食べる", hiragana: "たべる", category: "spring_word_verb01", emoji: "🍴" },
  { id: 367, english: "eat breakfast", kanji: "朝食を食べる", hiragana: "ちょうしょくをたべる", category: "spring_word_verb01", emoji: "🍳" },
  { id: 368, english: "eat lunch", kanji: "昼食を食べる", hiragana: "ちゅうしょくをたべる", category: "spring_word_verb01", emoji: "🍱" },
  { id: 369, english: "eat dinner", kanji: "夕食を食べる", hiragana: "ゆうしょくをたべる", category: "spring_word_verb01", emoji: "🍲" },
  { id: 370, english: "drink", kanji: "飲む", hiragana: "のむ", category: "spring_word_verb01", emoji: "🥛" },
  { id: 371, english: "sleep", kanji: "寝る", hiragana: "ねる", category: "spring_word_verb01", emoji: "😴" },
  { id: 372, english: "cook", kanji: "料理をする", hiragana: "りょうりをする", category: "spring_word_verb01", emoji: "👨‍🍳" },
  { id: 373, english: "go to ~", kanji: "〜へ行く", hiragana: "〜へいく", category: "spring_word_verb01", emoji: "🏃" },
  { id: 374, english: "go to bed", kanji: "寝る", hiragana: "ねる", category: "spring_word_verb01", emoji: "🛌" },
  { id: 375, english: "go shopping", kanji: "買い物に行く", hiragana: "かいものにいく", category: "spring_word_verb01", emoji: "🛍️" },
  { id: 376, english: "go skiing", kanji: "スキーに行く", hiragana: "すきーにいく", category: "spring_word_verb01", emoji: "⛷️" },
  { id: 377, english: "go fishing", kanji: "釣りに行く", hiragana: "つりにいく", category: "spring_word_verb01", emoji: "🎣" },
  { id: 378, english: "go swimming", kanji: "泳ぎに行く", hiragana: "およぎにいく", category: "spring_word_verb01", emoji: "🏊" },
  { id: 379, english: "go hiking", kanji: "ハイキングに行く", hiragana: "はいきんぐにいく", category: "spring_word_verb01", emoji: "🥾" },
  { id: 380, english: "go to the movies", kanji: "映画に行く", hiragana: "えいがにいく", category: "spring_word_verb01", emoji: "🎬" },
  { id: 381, english: "get to ~", kanji: "〜に着く", hiragana: "〜につく", category: "spring_word_verb01", emoji: "📍" },
  { id: 382, english: "get up", kanji: "起きる", hiragana: "おきる", category: "spring_word_verb01", emoji: "⏰" },
  { id: 383, english: "wake up", kanji: "目覚める", hiragana: "めざめる", category: "spring_word_verb01", emoji: "👀" },
  { id: 384, english: "live in ~", kanji: "〜に住む", hiragana: "〜にすむ", category: "spring_word_verb01", emoji: "🏠" },
  { id: 385, english: "listen to ~", kanji: "〜を聞く", hiragana: "〜をきく", category: "spring_word_verb01", emoji: "🎧" },
  { id: 386, english: "look at ~", kanji: "〜を見る（止まっている物）", hiragana: "〜をみる", category: "spring_word_verb01", emoji: "🖼️" },
  { id: 387, english: "watch", kanji: "〜を見る（動いている物）", hiragana: "〜をみる", category: "spring_word_verb01", emoji: "📺" },
  { id: 388, english: "watch TV", kanji: "テレビを見る", hiragana: "てれびをみる", category: "spring_word_verb01", emoji: "📺" },
  { id: 389, english: "see", kanji: "見る、会う", hiragana: "みる、あう", category: "spring_word_verb01", emoji: "👁️" },
  { id: 390, english: "wash", kanji: "洗う", hiragana: "あらう", category: "spring_word_verb01", emoji: "🧼" },
  { id: 391, english: "wash the dishes", kanji: "皿を洗う", hiragana: "さらをあらう", category: "spring_word_verb01", emoji: "🍽️" },
  { id: 392, english: "want", kanji: "欲しい", hiragana: "ほしい", category: "spring_word_verb01", emoji: "🎁" },
  { id: 393, english: "make", kanji: "作る", hiragana: "つくる", category: "spring_word_verb01", emoji: "🛠️" },
  { id: 394, english: "make cookies", kanji: "クッキーを作る", hiragana: "くっきーをつくる", category: "spring_word_verb01", emoji: "🍪" },
];
