const WORDS_spring_word_verb04 = [

 { id: 400, english: "after school", kanji: "放課後", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 401, english: "over there", kanji: "あそこで", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 402, english: "All right.", kanji: "いいですよ。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 403, english: "Of course.", kanji: "もちろん。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 404, english: "Thank you for ~.", kanji: "〜をありがとう。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 405, english: "You’re welcome.", kanji: "どういたしまして。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 406, english: "Here you are.", kanji: "はい、どうぞ。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 407, english: "Here it is.", kanji: "はい、どうぞ。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 408, english: "Good morning.", kanji: "おはようございます。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 409, english: "Good night.", kanji: "おやすみなさい。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 410, english: "Have a nice (good) ~.", kanji: "よい〜を。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 411, english: "It’s time for ~.", kanji: "〜の時間です。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 412, english: "Pass me the ~.", kanji: "〜を取ってください。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 413, english: "in the morning", kanji: "朝に、午前中に", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 414, english: "in the afternoon", kanji: "午後に", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 415, english: "at night", kanji: "夜に", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 416, english: "Welcome to ~.", kanji: "ようこそ〜へ。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 417, english: "Me, too.", kanji: "私も。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 418, english: "You, too.", kanji: "あなたも。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 419, english: "a little", kanji: "少し", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 420, english: "a lot of ~", kanji: "たくさんの〜", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 421, english: "on TV", kanji: "テレビで", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 422, english: "by（乗り物）", kanji: "乗り物で", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 423, english: "It’s mine.", kanji: "私のものです。", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 424, english: "from A to B", kanji: "AからBまで", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
 { id: 425, english: "late for ~", kanji: "〜に遅れる", hiragana: "", category: "spring_word_verb04", emoji: "📝" },
  ];
